# Generated by Django 5.1.7 on 2025-03-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tootekategooria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Toode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
                ('kogus', models.PositiveIntegerField(default=0)),
                ('partii_number', models.CharField(max_length=100, unique=True)),
                ('aegumiskuupaev', models.DateField()),
                ('qr_kood', models.ImageField(blank=True, upload_to='qr_codes')),
                ('kategooria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladu.tootekategooria')),
            ],
        ),
    ]
