# Generated by Django 5.1.7 on 2025-03-12 22:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladu', '0003_toode_kategooria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_kood', models.CharField(max_length=255)),
                ('skaneeritud_aeg', models.DateTimeField(default=django.utils.timezone.now)),
                ('kasutaja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('toode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladu.toode')),
            ],
        ),
    ]
