# Generated by Django 5.1.7 on 2025-03-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladu', '0004_scanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='toode',
            name='pilt',
            field=models.ImageField(blank=True, null=True, upload_to='toote_pildid/'),
        ),
    ]
